'''
try 

tenta fazer aquilo

except

se dÃ¡ erro

else

sem erro

finally

independente de erro ou nao, sera mostrado

'''


# except Exception as erro => guarda o nome do erro na variavel
# except (erro 1 , erro 2)